dist: focal
os: linux

language: python
python:
  - "3.7"
  - "3.10"

# install system dependencies here with apt-get.
before_install:
  - sudo ./provision/debian.sh
  - python -m pip install --upgrade pip

# install python dependencies including this package in the travis
# virtualenv
install:

  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]];
        then ./provision/python3.sh;
        fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.10 ]];
        then ./provision/python3.sh;
        fi
  - pip install .[pocketsphinx]

# commands to run the testing suite. if any of these fail, travic lets us know
script:
  - cd tests && make && cd -
  - nosetests --with-coverage --cover-package=extratextract
  - cd tests && pytest && cd -
#  - pycodestyle extratextract/ bin/extratextract
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]];
        then cd docs && make html && cd -;
        fi

# commands to run after the tests successfully complete
after_success:
  - coveralls
